# Generated by Django 4.0.3 on 2022-04-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('it_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('possessed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=255)),
                ('p_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=31)),
                ('lname', models.CharField(max_length=31)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequests',
            fields=[
                ('p_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('iname', models.CharField(max_length=31)),
                ('quant', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('arg', models.CharField(max_length=255)),
                ('app_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Approver_ID', to='api.member')),
                ('sub_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Submitter_ID', to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=31)),
                ('password', models.CharField(max_length=31)),
                ('member_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.member')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('in_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('app_date', models.DateField()),
                ('ful_Status', models.CharField(choices=[('Pending', 'Pending'), ('Purchased', 'Purchased'), ('Fulfilled', 'Fulfulled')], max_length=255)),
                ('ful_date', models.DateField()),
                ('approved_pr', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.purchaserequests')),
            ],
        ),
    ]
