# Generated by Django 4.0.3 on 2022-04-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_purchaserequests_purchaserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='in_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='it_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='p_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
