# Generated by Django 4.0.3 on 2022-04-06 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_invoice_in_id_alter_item_it_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='approved_pr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='member_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.member'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='app_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Approver_ID', to='api.member'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='sub_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Submitter_ID', to='api.member'),
        ),
    ]
