# Generated by Django 4.0.3 on 2022-04-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_invoice_approved_pr_alter_logininfo_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='app_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Approver_ID', to='api.member'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='sub_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Submitter_ID', to='api.member'),
        ),
    ]
