# Generated by Django 4.0.3 on 2022-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_purchaserequest_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='memType',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
