# Generated by Django 4.0.3 on 2022-04-15 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_logininfo_memtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_invoice', to='api.invoice'),
        ),
    ]
