# Generated by Django 4.0.3 on 2022-04-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_inv'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='app_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ful_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
